### ISSUE TITLE
HTML Template

### ISSUE THREAD

**Issue by guilhermesoper** [secrethash/dropmenu#1]
What about to create something like an HTML template in order to customize the entire menu HTML output? Maybe not everyone, like me, would like to use a  Bootstrap Supported menus. In my case, I already have a dashboard admin theme which has a menu with a little bit different HTML structure, like this:

```
<li class="active">
    <a href="#" class="js-sub-menu-toggle">
        <i class="fa fa-edit fa-fw"></i>
        <span class="text">Parent Item</span>
        <i class="toggle-icon fa fa-angle-down"></i>
    </a>
    <ul class="sub-menu open">
        <li class="active">
            <a href="#">
                <span class="text">Item Child 1</span>
            </a>
        </li>
    </ul>
    <ul class="sub-menu open">
        <li>
            <a href="#">
                <span class="text">Item Child 2</span>
            </a>
        </li>
    </ul>
</li>
```
Tks!

**Comment by secrethash** [comment]
That looks like a great idea, and might replace the settings injection method that I currently use in DropMenu. I will keep this in Consideration. 😊


## For Now
As I mentioned, __DropMenu__  uses __Settings Injection__  method to generate a Dropdown Menu for Navigation. Even if you don't need the basic Bootstrap Menu, still you can use it as __settings injection__  provide flexibility to it.


## What to Do
Here's a step by step method to generate a menu like you want:
1. As initial UL `<ul>` element is not generated by DropMenu so that you can customise it as you want. It starts from the LI `<li>` element.
2. Customising `<a href="#" class="js-sub-menu-toggle">`: set the `link_attr` Coloumn in the database table to `class="js-sub-menu-toggle"`. It helps to define the attributes that links will include. And as, in your case, only the parent has this, only define it for the parent.
3. Follow the ***Settings Injection*** to inject settings. Like this:
```php
<?php

 //--SomeThingsAndLogics--//

 $set['icon']['suffix'] = '"></i><span class="text">'; // What comes before the text and after the icon value.
 $set['icon']['line_end'] = '</span>'; // What comes after the text
 $set['child']['ul_attributes'] = 'class="sub-menu open"'; //Attributes for Child's UL element

<ul class="someClass">
    {!! Dropmenu::display('nav:admin', $set) !!}
</ul>

```
thats it.
 

_Sent from my LENOVO Lenovo K50a40 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by secrethash** [comment]
Read the full docs at: [DropMenu Docs](https://secrethash.github.io/dropmenu)


_Sent from my LENOVO Lenovo K50a40 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
